# home/<username>/git/container-stacks-manager/csm.ini

# CSM version
CSM_VERSION=0.4.2

# Container runtime (docker or podman, leave blank to choose during installation)
CSM_CONTAINER_RUNTIME=

# GID and UID for the stacks group and user
CSM_STACKS_GID=2000
CSM_STACKS_UID=2000

# Root directory for all stack files
CSM_ROOT_DIR="/srv/stacks"
CSM_BACKUPS_DIR="${CSM_ROOT_DIR}/.backups"
CSM_CONFIGS_DIR="${CSM_ROOT_DIR}/.configs"
CSM_MODULES_DIR="${CSM_ROOT_DIR}/.modules"
CSM_SECRETS_DIR="${CSM_ROOT_DIR}/.secrets"

# Example file templates
CSM_ENV_TEMP="${CSM_CONFIGS_DIR}/example.env"
CSM_ENV_PROD=".env"
CSM_COMPOSE_TEMP="${CSM_CONFIGS_DIR}/example-compose.yml"
CSM_COMPOSE_PROD="compose.yml"

# Container orchestration settings
CSM_BACKUP_MAX_AGE=30  # days
CSM_BACKUP_COMPRESSION="zip"
CSM_NETWORK_NAME="csm_network"
CSM_NETWORK_SUBNET="172.20.0.0/16"
CSM_VOLUME_DRIVER="local"
CSM_VOLUME_LABEL="csm_volume"

# Preconfigured module settings
CSM_MODULE_SOURCE="gitlab"
CSM_MODULE_BRANCH="main"
CSM_MODULE_REPO_NAME="csm_stack_modules"
CSM_MODULE_UPDATE_INTERVAL=7  # days
CSM_MODULE_GITHUB_OWNER='techtinker-homelab'
CSM_MODULE_GITHUB_URL="https://github.com/${CSM_MODULE_REPO_NAME}"
CSM_MODULE_GITHUB_RAW="${CSM_MODULE_GITHUB_URL}/raw/${CSM_MODULE_BRANCH}"
CSM_MODULE_GITLAB_OWNER='techtinker'
CSM_MODULE_GITLAB_URL="https://www.gitlab.com/${CSM_MODULE_GITLAB_OWNER}/${CSM_MODULE_REPO_NAME}"
CSM_MODULE_GITLAB_RAW="${CSM_MODULE_GITLAB_URL}/-/raw/${CSM_MODULE_BRANCH}"
