# 'dozzle' docker compose created to work with - https://gitlab.com/techtinker/container-stack-manager

networks:
  internal_only:
    external: true

services:
  app:
    image: amir20/dozzle:latest
    networks:
      - internal_only
    ports:
      - 8888:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    environment:
      DOZZLE_MODE: swarm
      username: username
      password: password
    deploy:
      mode: global
    # labels:
    #   traefik.enable: "true"
    #   traefik.http.routers.dozzle.entrypoints: webnonsec
    #   traefik.http.routers.dozzle.tls.certresolver: letsencrypt
    #   traefik.http.routers.dozzle.rule: Host(`dozzle.${var_domain1}`)
    #   traefik.http.routers.dozzle.service: dozzle
    #   traefik.http.services.dozzle.loadbalancer.server.port: "8080"
